# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
                ('companyDesc', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProtocolBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolNo', models.CharField(max_length=15)),
                ('documentNo', models.CharField(max_length=30)),
                ('documentDesc', models.CharField(max_length=300)),
                ('documentDate', models.DateTimeField(verbose_name='document date')),
                ('documentValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('documentFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comanyFrom', to='protocolbook.Company')),
                ('documentTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comanyTo', to='protocolbook.Company')),
            ],
        ),
    ]
